version: '3.8'

services:
  app:
    image: node:22
    container_name: server
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run start"