export interface CompanyModel {
  companyId: number;
  companyName: string;
  companyLocation: string;
}


/*
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COMPANY](
	[COMPANY_ID] [int] NOT NULL,
	[COMPANY_NAME] [varchar](35) NOT NULL,
	[COMPANY_LOCATION] [varchar](128) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COMPANY] ADD PRIMARY KEY CLUSTERED
(
	[COMPANY_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
 */
