export interface DepartmentModel {
  deptId: number;
  deptName: string;
  empId: number;
}

/*
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEPARTMENT](
	[DEPT_ID] [int] NOT NULL,
	[DEPT_NAME] [varchar](64) NOT NULL,
	[EMP_ID] [int] NOT NULL,
	[PLANT_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPARTMENT] ADD PRIMARY KEY CLUSTERED
(
	[DEPT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPARTMENT]  WITH CHECK ADD FOREIGN KEY([EMP_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMP_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[DEPARTMENT]  WITH CHECK ADD  CONSTRAINT [FK_DEPARTMENT_PLANT] FOREIGN KEY([PLANT_ID])
REFERENCES [dbo].[PLANT] ([PLANT_ID])
GO
ALTER TABLE [dbo].[DEPARTMENT] CHECK CONSTRAINT [FK_DEPARTMENT_PLANT]
GO
 */
