export interface OrderModel {
  microcomponentSKU: number;
  companyId: number;
  orderDate: string;
  orderQuantity: number;
}

/*
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDERS](
	[MC_SKU] [int] NOT NULL,
	[COMPANY_ID] [int] NOT NULL,
	[ORDER_DATE] [date] NOT NULL,
	[ORDER_QUANTITY] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDERS] ADD  CONSTRAINT [PK_ORDERS] PRIMARY KEY CLUSTERED
(
	[MC_SKU] ASC,
	[COMPANY_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDERS]  WITH CHECK ADD FOREIGN KEY([COMPANY_ID])
REFERENCES [dbo].[COMPANY] ([COMPANY_ID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[ORDERS]  WITH CHECK ADD FOREIGN KEY([MC_SKU])
REFERENCES [dbo].[MICRO_COMPONENTS] ([MC_SKU])
ON UPDATE CASCADE
GO

 */
