export interface PermissionLevelModel {
  permissionLevelId: number;
  permissionLevelName: string;
}

/*
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERMISSION_LEVEL](
	[PL_ID] [int] NOT NULL,
	[PERMISSION_LEVEL] [varchar](16) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERMISSION_LEVEL] ADD PRIMARY KEY CLUSTERED
(
	[PL_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

 */
