export interface PlantModel {
  plantId: number;
  plantAddress: string;
  plantZipCode: string;
  managerId: number;
}

/*
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PLANT](
	[PLANT_ID] [int] NOT NULL,
	[PLANT_ADDRESS] [varchar](92) NOT NULL,
	[PLANT_ZIPCODE] [varchar](5) NOT NULL,
	[MANAGER_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PLANT] ADD PRIMARY KEY CLUSTERED
(
	[PLANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PLANT]  WITH CHECK ADD FOREIGN KEY([MANAGER_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMP_ID])
ON UPDATE CASCADE
GO

 */
