export interface RoleModel {
  roleId: number;
  roleTitle: string;
  permissionLevelId: number;
}

/*
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROLES](
	[ROLE_ID] [int] NOT NULL,
	[ROLE_TITLE] [varchar](32) NOT NULL,
	[PL_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ROLES] ADD PRIMARY KEY CLUSTERED
(
	[ROLE_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ROLES]  WITH CHECK ADD FOREIGN KEY([PL_ID])
REFERENCES [dbo].[PERMISSION_LEVEL] ([PL_ID])
ON UPDATE CASCADE
GO

 */
