export interface VendorModel {
  vendorId: number;
  vendorName: string;
  vendorAddress: string;
  vendorZipCode: string;
}

/*
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VENDOR](
	[VENDOR_ID] [int] NOT NULL,
	[VENDOR_NAME] [varchar](32) NOT NULL,
	[VENDOR_ADDRESS] [varchar](64) NOT NULL,
	[VENDOR_ZIPCODE] [varchar](5) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENDOR] ADD PRIMARY KEY CLUSTERED
(
	[VENDOR_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

 */
